include: package:effective_dart/analysis_options.yaml

analyzer:
  exclude:
    - lib/generated/**

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    prefer_expression_function_bodies: true
    prefer_typing_uninitialized_variables: true
    use_function_type_syntax_for_parameters: true
    avoid_function_literals_in_foreach_calls: false
