name: Create version tag
on:
  push:
    branches:
      - release
      - ci_test

jobs:
  prep_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Extract version string
        run: |
          export VERSION=$(cat pubspec.yaml | awk '/version:/ {print $2}' | sed 's/+1//g')
          export DATE=$(printf '%(%Y%m%d)T\n' -1)

      #- uses: BobAnkh/auto-generate-changelog@master
      #  with:
      #    REPO_NAME: 'blockbasti/just_another_workout_timer'
      #    ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #    PATH: '/fastlane/metadata/android/en-US/changelogs/${{env.DATE}}.txt'
      #    COMMIT_MESSAGE: 'docs: update release notes'
      #    TYPE: 'feat:Feature,fix:Bug Fixes,docs:Documentation,refactor:Refactor,perf:Performance Improvements'

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          git-message: 'chore(release): {version}'
          git-user-name: 'Awesome Changelog Action'
          git-user-email: 'awesome_changelog@github.actions.com'
          preset: 'angular'
          tag-prefix: 'v'
          output-file: 'CHANGELOG.md'
          release-count: 5
          #version-file: './my_custom_version_file.json'
          #version-path: 'path.to.version'
          skip-on-empty: 'false'
          skip-version-file: 'true'
          skip-commit: 'false'